Version: '3.18'

services:

  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_USER: admin
      REDIS_PASSWORD: password
    networks:
      - enum-verse_web_net
    restart: on-failure

  postgresDB:
    container_name: enum_postgres_db
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: default_db
      PGDATA: /data/postgres
    volumes:
      - enumverse_db_data:/data/postgres
    networks:
      - enum-verse_web_net
    ports:
      - "5431:5432"
    restart: always

  mongodb:
    container_name: mongo_demo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - enum-verse_web_net
    restart: on-failure

  #keycloak:
    #container_name: keycloak_server
    #image: quay.io/keycloak/keycloak:latest
    #command: [ 'start-dev' ]
    #ports:
     # - "8090:8090"
    #networks:
     # - enum-verse_web_net
    #environment:
      #KEYCLOAK_ADMIN: admin
      #KEYCLOAK_ADMIN_PASSWORD: admin

#  eureka-server:
#    build: .
#    image: eureka-server
    #container_name: eureka-server
#    ports:
#      - "8761:8761"
#    networks:
#      - enum-verse_web_net

  api-gateway:
    build: .
    image: api-gateway
    #container_name: api-gateway
    ports:
      - "8080:8080"
    #depends_on:
    #  - eureka-server
    #     - "15672:15672" # RabbitMQ Management Console
    #   environment:
    #     RABBITMQ_DEFAULT_USER: admin
    #     RABBITMQ_DEFAULT_PASS: admin
    #   volumes:
    #     - ./rabbitmq_data:/var/lib/rabbitmq


 # app:
   # build: .
   # image: enumverse
   # ports:
    #  - "8081:8081"
    #env_file:
     # - .enum.env
   # links:
    #  - mongodb:app_db
    #depends_on:
     # - keycloak
     # - eureka-server
     # - postgresDB
     # - mongodb
   # networks:
    #  - enum-verse_web_net
      #volumes:
     # - .:/usr/src/app
   # restart: on-failure

#networks:
#  enum-verse_web_net:
#    name: local
#    driver: bridge

#volumes:
#  enumverse_db_data:
#nv_file:
#      - .enum.env
#    links:
 #     - mongodb:app_db
  #  depends_on:
   #   - keycloak
    #  - eureka-server
     # - postgresDB
     # - mongodb
   # networks:
   #   - enum-verse_web_net
   # volumes:
    #  - .:/usr/src/app
    #restart: on-failure

networks:
  enum-verse_web_net:
    name: local
    driver: bridge

volumes:
  enumverse_db_data: