#secret for the public manifest
kind: Secret
apiVersion: v1
metadata:
  name: spleet-public-prod-secrets
  namespace: spleet-public-frontend
  annotations:
    avp.kubernetes.io/path: "kv/data/public-prod"
    
type: Opaque
stringData:
  BASE_URL: <BASE_URL>
  DASHBOARD_DOMAIN: <DASHBOARD_DOMAIN>
  GOOGLE_MAP_KEY: <GOOGLE_MAP_KEY>
  RNPL_BASE_URL: <RNPL_BASE_URL_NEW>
  MAP_ID: <MAP_ID>
  CLOUDINARY_BASE_URL: <CLOUDINARY_BASE_URL>
  NODE_ENV: <NODE_ENV>
  NUXT_SITE_ENV: <NUXT_SITE_ENV>
  WELCOME_PAGE: <WELCOME_PAGE>


#secret for the backend manifest

kind: Secret
apiVersion: v1
metadata:
  name: backend-new-secrets
  namespace: prod
  annotations:
    avp.kubernetes.io/path: "kv/data/backend-prod"
type: Opaque
stringData:
  ADMINAPP_BASE_URL: <ADMINAPP_BASE_URL>
  ADMIN_EMAIL: <ADMIN_EMAIL>
  ALL_SPACES_CACHE_LIMIT: <ALL_SPACES_CACHE_LIMIT>
  ALL_SPACES_CACHE_PAGE: <ALL_SPACES_CACHE_PAGE>
  APPRUVE_ACCESS_TOKEN: <APPRUVE_ACCESS_TOKEN>
  APP_BASE_URL: <APP_BASE_URL>
  BUGSNAG_KEY: <BUGSNAG_KEY>
  CLODUINARY_API_SECRET: <CLODUINARY_API_SECRET>
  CLOUDINARY_API_KEY: <CLOUDINARY_API_KEY>
  CLOUDINARY_NAME: <CLOUDINARY_NAME>
  CONFIGURE_ACCESS_TOKEN: <CONFIGURE_ACCESS_TOKEN>
  CONFIGURE_BASE_URL: <CONFIGURE_BASE_URL>
  DB_HOST: <DB_HOST>
  DB_NAME: <DB_NAME>
  DB_PASS: <DB_PASS>
  DB_PORT: <DB_PORT>
  DB_TYPE: <DB_TYPE>
  DB_USER: <DB_USER>
  DRIVERS_LICENSE_VERIFICATION_API_STATUS: <DRIVERS_LICENSE_VERIFICATION_API_STATUS>
  FACEBOOK_APP_ID: <FACEBOOK_APP_ID>
  FACEBOOK_APP_SECRET: <FACEBOOK_APP_SECRET>
  FLUTTERWAVE_HASH: <FLUTTERWAVE_HASH>
  FLUTTERWAVE_TEST_SECRET: <FLUTTERWAVE_TEST_SECRET>
  FLUTTERWAVE_TRANSACTION_FEE: <FLUTTERWAVE_TRANSACTION_FEE>
  FRONTEND_MICRO_SITE_BASE_URL: <FRONTEND_MICRO_SITE_BASE_URL>
  GOOGLE_CLIENT_ID: <GOOGLE_CLIENT_ID>
  GOOGLE_SECRET: <GOOGLE_SECRET>
  IDENTITYPASS_API_KEY: <IDENTITYPASS_API_KEY>
  IDENTITYPASS_APP_ID: <IDENTITYPASS_APP_ID>
  IDENTITYPASS_BASE_URL: <IDENTITYPASS_BASE_URL>
  INTERCOM_ACCESS_TOKEN: <INTERCOM_ACCESS_TOKEN>
  LOAN_PUBLIC_LOGIN_URL: <LOAN_PUBLIC_LOGIN_URL>
  MANDRILL_SECRET_KEY: <MANDRILL_SECRET_KEY>
  METAMAP_WEBHOOK_SECRET: <METAMAP_WEBHOOK_SECRET>
  NIN_VERIFICATION_API_STATUS: <NIN_VERIFICATION_API_STATUS>
  PASSPORT_VERIFICATION_API_STATUS: <PASSPORT_VERIFICATION_API_STATUS>
  PAYSTACK_TEST_SECRET: <PAYSTACK_TEST_SECRET>
  PROJECT_ID: <PROJECT_ID>
  REDIS_HOST: <NEW_REDIS_HOST>
  REDIS_PORT: <REDIS_PORT>
  RNPL_URL: <RNPL_URL>
  RESET_PASSWORD_LINK: <RESET_PASSWORD_LINK>
  SECRET: <SECRET>
  SERVER_ENV: <SERVER_ENV>
  SERVICE_NAME: <SERVICE_NAME>
  SPECTA_API_KEY: <SPECTA_API_KEY>
  SPECTA_MERCHANT_ID: <SPECTA_MERCHANT_ID>
  SPEKTRA_ACCOUNT_NAME: <SPEKTRA_ACCOUNT_NAME>
  SPEKTRA_BASE_URL: <SPEKTRA_BASE_URL>
  SPEKTRA_CHECKOUT_BASE_URL: <SPEKTRA_CHECKOUT_BASE_URL>
  SPEKTRA_PUBLIC_KEY: <SPEKTRA_PUBLIC_KEY>
  SPEKTRA_SECRET: <SPEKTRA_SECRET>
  SPLEET_FRONTEND: <SPLEET_FRONTEND>
  SPLEET_RECOVA_TOKEN: <SPLEET_RECOVA_TOKEN>
  TERMII_API_KEY: <TERMII_API_KEY>
  TERMII_BASE_URL: <TERMII_BASE_URL>
  TERMII_SMS_SENDER_ID: <TERMII_SMS_SENDER_ID>
  TEST_APPRUVE_TOKEN: <TEST_APPRUVE_TOKEN>
  TOKENEXPIRATIONTIME: <TOKENEXPIRATIONTIME>
  VAT: <VAT>
  VERIFYTOKENEXPIRATIONTIME: <VERIFYTOKENEXPIRATIONTIME>
  VERIFY_ADMIN_URL: <VERIFY_ADMIN_URL>
  VOTERS_CARD_VERIFICATION_API_STATUS: <VOTERS_CARD_VERIFICATION_API_STATUS>
  WEBAPP_BASE_URL: <WEBAPP_BASE_URL>
  WELCOME_MAIL_SENDER: <WELCOME_MAIL_SENDER>
  WITHHOLDING_TAX: <WITHHOLDING_TAX>
  RNPL_WEBHOOK_TOKEN: <RNPL_UPDATED_WEBTOKEN>
  RENT_DEFAULT_SECURITY_DEPOSIT_PERCENTAGE: <RENT_DEFAULT_SECURITY_DEPOSIT_PERCENTAGE>
  DAMAGES_SECURITY_DEPOSIT_PERCENTAGE: <DAMAGES_SECURITY_DEPOSIT_PERCENTAGE>
  RNPL_PAYMENT_TOKEN: <RNPL_PAYMENT_TOKEN>
  DEFAULT_BOOKING_FEE: <DEFAULT_BOOKING_FEE>
  BANK_STATEMENT_PERIOD: <BANK_STATEMENT_PERIOD>
  OKRA_URL: <OKRA_URL>
  OKRA_SECRET_KEY: <OKRA_SECRET_KEY>
  MONO_URL: <MONO_URL>
  MONO_SECRET_KEY: <MONO_SECRET_KEY>
  MONO_WEBHOOK_SECRET: <MONO_WEBHOOK_SECRET>
  BUCKET_KEY_FILE: <BUCKET_KEY_FILE>
  GOOGLE_BUCKET_ID: <GOOGLE_BUCKET_ID>



#secret for the frontend manifest
kind: Secret
apiVersion: v1
metadata:
  name: frontend-secrets
  namespace: prod
  annotations:
    avp.kubernetes.io/path: "kv/data/frontend-secrets"
type: Opaque
stringData:
   BASE_URL: <BASE_URL>
   CLOUDINARY_PRESET: <CLOUDINARY_PRESET>
   CLOUDINARY_URL: <CLOUDINARY_URL>
   CONFIGURE_LOGIN: <CONFIGURE_LOGIN>
   EMAIL_VERIFICATION_PAGE: <EMAIL_VERIFICATION_PAGE_NEW>
   FLUTTERWAVE_PUBLIC: <FLUTTERWAVE_PUBLIC>
   FORGET_PASSWORD_PAGE: <FORGET_PASSWORD_PAGE>
   GOOGLE_ANALYTICS_ID: <GOOGLE_ANALYTICS_ID>
   GOOGLE_CLIENT_ID: <GOOGLE_CLIENT_ID>
   GOOGLE_MAP_KEY: <GOOGLE_MAP_KEY>
   METAMAP_CLIENT_ID: <METAMAP_CLIENT_ID>
   METAMAP_FLOW_ID: <METAMAP_FLOW_ID_UPDATED>
   PAYSTACK_PUBLIC: <PAYSTACK_PUBLIC>
   VERIFY_CALLBACKURL: <VERIFY_CALLBACKURL_NEW>
   RNPL_BASE_URL: <RNPL_PROD_BASE_URL>
   OKRA_KEY: <OKRA_KEY>
   OKRA_TOKEN: <OKRA_TOKEN>
   OKRA_NAME: <OKRA_NAME>
   OKRA_ENV: <OKRA_ENV>
   IS_DEV: <IS_DEV>
   PUBLIC_DOMAIN: <PUBLIC_DOMAIN>
   DOMAIN: <DOMAIN>


#secret for the rnpl manifest

kind: Secret
apiVersion: v1
metadata:
  name: rnpl-secrets
  namespace: rnpl
  annotations:
    avp.kubernetes.io/path: "kv/data/rnpl"
    avp.kubernetes.io/secret-version: "42" 
type: Opaque
stringData:
  ADMINAPP_BASE_URL: <ADMINAPP_BASE_URL>
  APPRUVE_ACCESS_TOKEN: <APPRUVE_ACCESS_TOKEN>
  APPRUVE_URL: <APPRUVE_URL>
  BANK_STATEMENT_PERIOD: <BANK_STATEMENT_PERIOD>
  CLOUDINARY_API_KEY: <CLOUDINARY_API_KEY>
  CLOUDINARY_API_SECRET: <CLOUDINARY_API_SECRET>
  CLOUDINARY_NAME: <CLOUDINARY_NAME>
  DATABASE_HOST: <DATABASE_HOST>
  DATABASE_NAME: <DATABASE_PROD>
  DATABASE_PASSWORD: <DATABASE_PASSWORD>
  DATABASE_PORT: <DATABASE_PORT>
  DATABASE_TYPE: <DATABASE_TYPE>
  DATABASE_USERNAME: <DATABASE_USERNAME>
  DEV_URL: <DEV_URL>
  ENCRYPTION_ALGORITHM: <ENCRYPTION_ALGORITHM>
  ENCRYPTION_IV: <ENCRYPTION_IV_UPDATE>
  ENCRYPTION_KEY: <ENCRYPTION_KEY_UPDATE>
  ENCRYPTION_SALT: <UPDATED_SALT>
  IDENTITY_PASS_BASE_URL: <IDENTITY_PASS_BASE_URL_UPDATED>
  IDENTITY_PASS_SECRET_KEY: <IDENTITY_PASS_SECRET_KEY_UPDATED>
  JWT_SECRET: <JWT_SECRET>
  MANDRILL_SECRET_KEY: <MANDRILL_SECRET_KEY>
  MARKETPLACE_URL: <MARKETPLACE_UPDATED_URL>
  OKRA_URL: <OKRA_URL>
  PAYMENT_TOKEN: <NEW_PAYMENT_TOKEN>
  PERICULUM_CLIENT_ID: <UPDATED_PERICULUM_CLIENT_ID>
  PERICULUM_CLIENT_SECRET: <UPDATED_PERICULUM_CLIENT_SECRET>
  PERICULUM_TOKEN_URL: <UPDATED_PERICULUM_TOKEN_URL>
  PERICULUM_URL: <PERICULUM_URL>
  PORT: <PORT>
  REDIS_HOST: <UPDATED_REDIS_HOST>
  REDIS_PORT: <REDIS_PORT>
  SERVER_ENV: <SERVER_ENV>
  TERMII_API_KEY: <TERMII_API_KEY>
  TERMII_SENDER_ID: <TERMII_SENDER_ID>
  TERMII_URL: <TERMII_URL>
  TOKEN_EXPIRATION_TIME: <TOKEN_EXPIRATION_TIME>
  WEBHOOK_TOKEN: <WEBHOOK_TOKEN_UPDATED>
  VFD_BASE_URL: <VFD_NEW_BASE_URL>
  VFD_KEY: <VFD_UPDATED_KEY>
  VFD_WALLET_CREDENTIAL: <VFD_UPDATED_WALLET_CREDENTIAL>
  BANK_ACCOUNT_ROUTE: <BANK_ACCOUNT_ROUTE>
  CRC_URL: <CRC_URL>
  CRC_USERNAME: <CRC_USERNAME>
  CRC_PASSWORD: <CRC_PASSWORD>
  INSTITUTION_CODE: <INSTITUTION_CODE_NEW>
  SPLEET_RECOVA_TOKEN: <SPLEET_RECOVA_TOKEN_NEW>
  RECOVA_DIRECT_DEBIT_TOKEN: <RECOVA_DIRECT_DEBIT_TOKEN_NEW>
  RECOVA_BASE_URL: <RECOVA_BASE_URL_NEW>
  SPLEET_VFD_ACCOUNT_DETAILS_ID: <SPLEET_VFD_ACCOUNT_DETAILS_ID>
  IDENTITY_PASS_APP_ID: <IDENTITY_PASS_APP_ID>
  IDENTITY_PASS_APP_KEY: <IDENTITY_PASS_APP_KEY_UPDATED>
  OKRA_SECRET_KEY: <OKRA_SECRET_KEY>
  VFD_AUTH_TOKEN: <VFD_AUTH_TOKEN>
  METAMAP_WEBHOOK_SECRET: <METAMAP_UPDATED_WEBHOOK>
  VFD_IP_ADDRES: <VFD_IP_ADDRES>
  MONO_SECRET_KEY: <MONO_SECRET_KEY>
  MONO_URL: <MONO_URL>
  MONO_WEBHOOK_SECRET: <MONO_WEBHOOK_SECRET>
  GCP_PROJECT_ID: <GCP_PROJECT_ID>
  GOOGLE_BUCKET_ID: <GOOGLE_BUCKET_ID>
  SPLEET_FRONTEND_URL: <SPLEET_FRONTEND_URL_NEW>
  